# yaml-language-server: $schema=https://schemas.brigade.sh/schemas-v2/project.json
apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: brigade-foundations
description: Brigade Foundations built with Brigade 2!
spec:
  eventSubscriptions:
  - source: brigade.sh/github
    qualifiers:
      repo: brigadecore/brigade-foundations
    types:
    - check_run:rerequested
    - check_suite:requested
    - check_suite:rerequested
  workerTemplate:
    git:
      cloneURL: https://github.com/brigadecore/brigade-foundations.git
